language: objective-c
osx_image: xcode8

env:
  matrix:
      - DESTINATION="OS=9.1,name=iPhone 6S"
      - DESTINATION="platform=iOS Simulator,name=iPhone 7 Plus"

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - rake test:ios DESTINATION="$DESTINATION"
  - pod lib lint --quick
